# -*- coding: utf-8 -*-
"""car_Safety.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jVBLF9vhhPXT6_ab5dAxMSyFOq-0BpWW
"""

import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

df=pd.read_csv(r'http://archive.ics.uci.edu/ml/machine-learning-databases/car/car.data',header=None,delimiter=',',names=['buying','maint','doors','persons','lug_boot','safety','CAR'])

from sklearn.preprocessing import LabelEncoder
lbc=LabelEncoder()
df["buying"]=lbc.fit_transform(df["buying"])
df["maint"]=lbc.fit_transform(df["maint"])
df["lug_boot"]=lbc.fit_transform(df["lug_boot"])
df["safety"]=lbc.fit_transform(df["safety"])
df["doors"]=lbc.fit_transform(df["doors"])
df["persons"]=lbc.fit_transform(df["persons"])
df['CAR'].unique()

df.applymap(np.isreal).head()

X=df.drop(['CAR'],axis=1).values
y=df['CAR'].values

from sklearn.model_selection import train_test_split
X_train, X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=0)

from sklearn.neighbors import KNeighborsClassifier
from math import sqrt
from sklearn.metrics import mean_squared_error
y1=lbc.fit_transform(df["CAR"])
rmse=[]
for k in range(20):
  k=k+1
  knn=KNeighborsClassifier(n_neighbors=k)
  knn.fit(X,y1)
  rmse.append(sqrt(mean_squared_error(y1,knn.predict(X))))
  print('K value ',k,'rmse ',sqrt(mean_squared_error(y1,knn.predict(X))))

knn=KNeighborsClassifier(n_neighbors=7)
knn.fit(X_train,y_train)
y_pred=knn.predict(X_test)

from sklearn import metrics
print("Accuracy ",metrics.accuracy_score(y,knn.predict(X)))

for xe, ye in zip(X,y):
  plt.scatter(xe,[ye]*
  len(xe),color="blue",marker="o",s=100)
for xe, ye in zip(X,knn.predict(X)):
  plt.scatter(xe,[ye]*
  len(xe),color="yellow",marker="*",s=10)
plt.show()